# Generated by Django 5.2 on 2025-10-09 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Goods',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название товара')),
                ('price', models.IntegerField(verbose_name='Цена товара')),
                ('relevans', models.DurationField(verbose_name='Период релевантности цены')),
                ('relevans_duration', models.DurationField(verbose_name='Сроки релевантности')),
            ],
            options={
                'verbose_name': 'Товар',
                'verbose_name_plural': 'Товары',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название услуги')),
                ('price', models.IntegerField(verbose_name='Цена услуги')),
                ('relevans', models.DurationField(verbose_name='Период релевантности цены')),
                ('relevans_duration', models.DurationField(verbose_name='Сроки релевантности')),
            ],
            options={
                'verbose_name': 'Услуга',
                'verbose_name_plural': 'Услуги',
                'ordering': ['id'],
            },
        ),
    ]
