# Generated by Django 5.2 on 2025-10-10 05:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ameneties', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='goods',
            name='relevans_duration',
        ),
        migrations.RemoveField(
            model_name='services',
            name='relevans_duration',
        ),
    ]
