# Generated by Django 5.2 on 2025-10-10 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ameneties', '0002_remove_goods_relevans_duration_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='goods',
            name='relevans',
        ),
        migrations.RemoveField(
            model_name='services',
            name='relevans',
        ),
        migrations.AddField(
            model_name='goods',
            name='relevant_from',
            field=models.DateField(blank=True, null=True, verbose_name='Релевантна с'),
        ),
        migrations.AddField(
            model_name='goods',
            name='relevant_to',
            field=models.DateField(blank=True, null=True, verbose_name='Релеванта по'),
        ),
        migrations.AddField(
            model_name='services',
            name='relevant_from',
            field=models.DateField(blank=True, null=True, verbose_name='Релевантна с'),
        ),
        migrations.AddField(
            model_name='services',
            name='relevant_to',
            field=models.DateField(blank=True, null=True, verbose_name='Релеванта по'),
        ),
    ]
