# Generated by Django 5.2 on 2025-10-09 11:14

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('booking', '0001_initial'),
        ('workers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BankPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Сумма')),
                ('is_chargeback', models.BooleanField(default=False, verbose_name='Возврат')),
                ('reference_number', models.CharField(blank=True, max_length=50, null=True, verbose_name='Номер платёжного поручения')),
                ('bank_name', models.CharField(blank=True, max_length=200, null=True, verbose_name='Название банка')),
                ('issue_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата оплаты')),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bank_payments', to='booking.agent', verbose_name='Контрагент')),
                ('booking_card', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bank_payments', to='booking.bookingcard', verbose_name='Карточка бронирования')),
            ],
            options={
                'verbose_name': 'Банковский перевод',
                'verbose_name_plural': 'Банковские переводы',
                'ordering': ['-issue_date'],
            },
        ),
        migrations.CreateModel(
            name='CardPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Сумма')),
                ('is_chargeback', models.BooleanField(default=False, verbose_name='Возврат')),
                ('cheque_id', models.CharField(blank=True, max_length=100, null=True, verbose_name='ID Чека')),
                ('issue_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата оплаты')),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='card_payments', to='booking.agent', verbose_name='Контрагент')),
                ('booking_card', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='card_payments', to='booking.bookingcard', verbose_name='Карточка бронирования')),
            ],
            options={
                'verbose_name': 'Оплата картой',
                'verbose_name_plural': 'Оплаты картой',
                'ordering': ['-issue_date'],
            },
        ),
        migrations.CreateModel(
            name='CashPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Сумма')),
                ('is_chargeback', models.BooleanField(default=False, verbose_name='Возврат')),
                ('cheque_id', models.CharField(blank=True, max_length=100, null=True, verbose_name='ID Чека')),
                ('issue_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата оплаты')),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cash_payments', to='booking.agent', verbose_name='Контрагент')),
                ('booking_card', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cash_payments', to='booking.bookingcard', verbose_name='Карточка бронирования')),
                ('received_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='received_cash_payments', to='workers.worker', verbose_name='Принял')),
            ],
            options={
                'verbose_name': 'Оплата наличными',
                'verbose_name_plural': 'Оплаты наличными',
                'ordering': ['-issue_date'],
            },
        ),
        migrations.CreateModel(
            name='PaymentOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Примечания')),
                ('bank_payments', models.ManyToManyField(blank=True, related_name='payment_orders', to='finance.bankpayment', verbose_name='Банковские переводы')),
                ('booking_card', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='payment_order', to='booking.bookingcard', verbose_name='Карточка бронирования')),
                ('card_payments', models.ManyToManyField(blank=True, related_name='payment_orders', to='finance.cardpayment', verbose_name='Оплаты картой')),
                ('cash_payments', models.ManyToManyField(blank=True, related_name='payment_orders', to='finance.cashpayment', verbose_name='Оплаты наличными')),
            ],
            options={
                'verbose_name': 'Платёжный ордер',
                'verbose_name_plural': 'Платёжные ордера',
                'ordering': ['-created_at'],
            },
        ),
    ]
