# Generated by Django 5.2 on 2025-10-09 11:14

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ameneties', '0001_initial'),
        ('documentation', '0001_initial'),
        ('workers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_title', models.CharField(max_length=100, unique=True, verbose_name='Полное название компании')),
                ('short_title', models.CharField(max_length=100, unique=True, verbose_name='Краткое наименование')),
                ('IIN_BIN', models.CharField(max_length=100, verbose_name='IIN | BIN')),
                ('adress', models.TextField(max_length=1000, verbose_name='Юридический адрес')),
                ('IBAN', models.CharField(max_length=34, verbose_name='IBAN')),
                ('BIC', models.CharField(max_length=100, verbose_name='Идентификатор Банка')),
                ('phone', models.CharField(db_index=True, max_length=20, verbose_name='Телефон')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
            ],
            options={
                'verbose_name': 'Контрагент',
                'verbose_name_plural': 'Контрагенты',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room', models.IntegerField(db_index=True, unique=True, verbose_name='Номер комнаты')),
                ('floor', models.IntegerField(blank=True, null=True, verbose_name='Этаж')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
            ],
            options={
                'verbose_name': 'Номер',
                'verbose_name_plural': 'Номера',
                'ordering': ['room'],
            },
        ),
        migrations.CreateModel(
            name='RoomCondition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('condition', models.CharField(max_length=100, unique=True, verbose_name='Состояние')),
                ('color', models.CharField(default='#808080', help_text='HEX цвет (#RRGGBB)', max_length=7, verbose_name='Цвет')),
                ('is_available', models.BooleanField(default=False, verbose_name='Доступен для бронирования')),
            ],
            options={
                'verbose_name': 'Состояние',
                'verbose_name_plural': 'Состояния',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='RoomType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Тип номера')),
                ('price', models.DecimalField(decimal_places=2, help_text='Цена в тенге', max_digits=10, verbose_name='Цена')),
                ('relevans', models.DurationField(verbose_name='Период релевантности цены')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
            ],
            options={
                'verbose_name': 'Тип номера',
                'verbose_name_plural': 'Типы номеров',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField(choices=[(1, 'Забронирован'), (2, 'Заселён'), (3, 'Выселен'), (4, 'Отмена')], default=1, verbose_name='Статус')),
                ('check_in', models.DateTimeField(blank=True, null=True, verbose_name='Дата заезда')),
                ('check_out', models.DateTimeField(blank=True, null=True, verbose_name='Дата выезда')),
                ('note', models.TextField(blank=True, max_length=1000, null=True, verbose_name='Комментарий')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('agent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='bookings', to='booking.agent', verbose_name='Контрагент')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_bookings', to='workers.worker', verbose_name='Создал')),
            ],
            options={
                'verbose_name': 'Бронирование',
                'verbose_name_plural': 'Бронирования',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Guest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, verbose_name='Имя')),
                ('last_name', models.CharField(max_length=100, verbose_name='Фамилия')),
                ('middle_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Отчество')),
                ('phone', models.CharField(db_index=True, max_length=20, validators=[django.core.validators.RegexValidator(message='Введите корректный номер телефона', regex='^\\+?1?\\d{9,15}$')], verbose_name='Телефон')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email')),
                ('date_of_birth', models.DateField(blank=True, null=True, verbose_name='Дата рождения')),
                ('gender', models.CharField(blank=True, choices=[('M', 'Мужской'), ('F', 'Женский'), ('O', 'Другой')], max_length=1, null=True, verbose_name='Пол')),
                ('blacklisted', models.BooleanField(default=False, help_text='Отметьте, если гость в чёрном списке', verbose_name='В чёрном списке')),
                ('blacklist_reason', models.TextField(blank=True, null=True, verbose_name='Причина блокировки')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Примечания')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата регистрации')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('documents', models.ManyToManyField(blank=True, related_name='guests', to='documentation.document', verbose_name='Документы')),
                ('nationality', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='guests', to='documentation.nationality', verbose_name='Гражданство')),
            ],
            options={
                'verbose_name': 'Гость',
                'verbose_name_plural': 'Гости',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BookingCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField(choices=[(1, 'Активна'), (2, 'Завершена'), (3, 'Отменена')], default=1, verbose_name='Статус')),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Общая сумма')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('bookings', models.ManyToManyField(related_name='booking_cards', to='booking.booking', verbose_name='Бронирования')),
                ('goods', models.ManyToManyField(blank=True, to='ameneties.goods', verbose_name='Товары приобретённые')),
                ('services', models.ManyToManyField(blank=True, to='ameneties.services', verbose_name='Услуги приобретены')),
                ('primary_guest', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='primary_booking_cards', to='booking.guest', verbose_name='Основной гость')),
            ],
            options={
                'verbose_name': 'Карточка бронирования',
                'verbose_name_plural': 'Карточки бронирования',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='booking',
            name='guest',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='bookings', to='booking.guest', verbose_name='Гость'),
        ),
        migrations.AddField(
            model_name='booking',
            name='room',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='bookings', to='booking.room', verbose_name='Номер'),
        ),
        migrations.AddField(
            model_name='booking',
            name='room_condition',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='bookings', to='booking.roomcondition', verbose_name='Состояние номера'),
        ),
        migrations.AddField(
            model_name='room',
            name='room_types',
            field=models.ManyToManyField(help_text='Выберите все доступные тарифы для этого номера', related_name='rooms', to='booking.roomtype', verbose_name='Доступные тарифы'),
        ),
        migrations.AddIndex(
            model_name='guest',
            index=models.Index(fields=['last_name', 'first_name'], name='booking_gue_last_na_b5afb7_idx'),
        ),
        migrations.AddIndex(
            model_name='guest',
            index=models.Index(fields=['phone'], name='booking_gue_phone_49c0ce_idx'),
        ),
        migrations.AddIndex(
            model_name='guest',
            index=models.Index(fields=['email'], name='booking_gue_email_575941_idx'),
        ),
    ]
