# Generated by Django 5.2 on 2025-10-10 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='roomtype',
            name='relevans',
        ),
        migrations.AddField(
            model_name='roomtype',
            name='relevant_from',
            field=models.DateField(blank=True, null=True, verbose_name='Релевантен с'),
        ),
        migrations.AddField(
            model_name='roomtype',
            name='relevant_to',
            field=models.DateField(blank=True, null=True, verbose_name='Релевантен до'),
        ),
    ]
