# Generated by Django 5.2 on 2025-10-09 11:14

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Nationality',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nationality', models.CharField(max_length=100, unique=True, verbose_name='Национальность')),
                ('code', models.CharField(blank=True, help_text='ISO код страны', max_length=3, null=True, verbose_name='Код страны')),
            ],
            options={
                'verbose_name': 'Национальность',
                'verbose_name_plural': 'Национальности',
                'ordering': ['nationality'],
            },
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('IIN', models.CharField(db_index=True, help_text='12 цифр без пробелов', max_length=12, unique=True, validators=[django.core.validators.RegexValidator(message='ИИН должен содержать ровно 12 цифр', regex='^\\d{12}$')], verbose_name='ИИН')),
                ('first_name', models.CharField(max_length=100, verbose_name='Имя')),
                ('last_name', models.CharField(max_length=100, verbose_name='Фамилия')),
                ('middle_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Отчество')),
                ('date_of_birth', models.DateField(blank=True, null=True, verbose_name='Дата рождения')),
                ('document_type', models.CharField(choices=[('passport', 'Паспорт'), ('id_card', 'Удостоверение личности')], default='passport', max_length=50, verbose_name='Тип документа')),
                ('number', models.CharField(db_index=True, max_length=100, verbose_name='Номер документа')),
                ('file', models.FileField(blank=True, help_text='Загрузите скан или фото документа', null=True, upload_to='documents/%Y/%m/', verbose_name='Скан документа')),
                ('url', models.URLField(blank=True, help_text='Внешняя ссылка на документ (если файл хранится в облаке)', max_length=1000, null=True, verbose_name='Ссылка на документ')),
                ('issued_date', models.DateField(blank=True, null=True, verbose_name='Дата выдачи')),
                ('expiry_date', models.DateField(blank=True, null=True, verbose_name='Срок действия до')),
                ('issued_by', models.CharField(blank=True, max_length=500, null=True, verbose_name='Кем выдан')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата загрузки')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Примечания')),
                ('nationality', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='documents', to='documentation.nationality', verbose_name='Гражданство')),
            ],
            options={
                'verbose_name': 'Документ гостя',
                'verbose_name_plural': 'Документы гостей',
                'ordering': ['-uploaded_at'],
                'indexes': [models.Index(fields=['IIN', 'document_type'], name='documentati_IIN_5ced6f_idx'), models.Index(fields=['number', 'document_type'], name='documentati_number_f355e9_idx')],
            },
        ),
    ]
