# Generated by Django 5.2 on 2025-10-09 11:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='JobTitle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, unique=True, verbose_name='Должность')),
                ('pay_per_hour', models.IntegerField(help_text='Указывается в тенге', verbose_name='Оплата за час работы')),
            ],
            options={
                'verbose_name': 'Должность',
                'verbose_name_plural': 'Должности',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='Worker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='ФИО сотрудника')),
                ('telegram_id', models.BigIntegerField(db_index=True, unique=True, verbose_name='Telegram ID')),
                ('telegram_username', models.CharField(blank=True, max_length=100, null=True, verbose_name='Telegram username')),
                ('is_working', models.BooleanField(default=False, verbose_name='Работает')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата добавления')),
                ('main_occupation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='workers', to='workers.jobtitle', verbose_name='Основная должность')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Ссылка на юзера')),
            ],
            options={
                'verbose_name': 'Сотрудник',
                'verbose_name_plural': 'Сотрудники',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.DateTimeField(auto_now_add=True, verbose_name='Начало смены')),
                ('finish', models.DateTimeField(blank=True, null=True, verbose_name='Время окончания')),
                ('jtitle', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reports', to='workers.jobtitle', verbose_name='Должность')),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reports', to='workers.worker', verbose_name='Сотрудник')),
            ],
            options={
                'verbose_name': 'Запись в табеле',
                'verbose_name_plural': 'Записи в табеле',
                'ordering': ['-start'],
            },
        ),
    ]
